import { useState, useMemo, useCallback, useEffect, useRef } from 'react'
import type { ExerciseDto } from '../../types/api'
import type { ExerciseResult } from '../../types/exercise'

export interface ImagePairExerciseProps {
  exercise: ExerciseDto
  onComplete?: (result: ExerciseResult | number) => void
  showInstruction?: boolean
}

type CardState = 'hidden' | 'revealed' | 'matched'

interface CardItem {
  backgroundId: number
  imageId: string
  backgroundColorHex: string | null
  state: CardState
}

/**
 * Image-pair game: cards show image + background. Match only when both background and image are the same.
 * Deck from exercise.imagePairDeck (generated by backend).
 */
export function ImagePairExercise({ exercise, onComplete, showInstruction = true }: ImagePairExerciseProps) {
  const deck = exercise.imagePairDeck
  if (!deck?.length) {
    return <p className="error">Invalid image-pair exercise: missing deck.</p>
  }

  const [phase, setPhase] = useState<'intro' | 'playing' | 'done'>('intro')
  const [cards, setCards] = useState<CardItem[]>([])
  const [moves, setMoves] = useState(0)
  const completedRef = useRef(false)

  const initialCards: CardItem[] = useMemo(
    () =>
      deck.map((c) => ({
        backgroundId: c.backgroundId,
        imageId: c.imageId,
        backgroundColorHex: c.backgroundColorHex,
        state: 'hidden' as CardState,
      })),
    [deck]
  )

  const startGame = useCallback(() => {
    setCards(initialCards.map((c) => ({ ...c, state: 'hidden' as CardState })))
    setPhase('playing')
    setMoves(0)
    completedRef.current = false
  }, [initialCards])

  const flippedIndices = useMemo(
    () => cards.map((c, i) => (c.state === 'revealed' ? i : -1)).filter((i) => i >= 0),
    [cards]
  )

  const isMatch = useCallback((a: CardItem, b: CardItem) => {
    return a.backgroundId === b.backgroundId && a.imageId === b.imageId
  }, [])

  const handleCardClick = useCallback(
    (index: number) => {
      if (phase !== 'playing') return
      const card = cards[index]
      if (card.state !== 'hidden') return
      if (flippedIndices.length >= 2) return

      setCards((prev) => {
        const next = prev.map((c, i) =>
          i === index ? { ...c, state: 'revealed' as CardState } : c
        )
        const nowRevealed = next
          .map((c, i) => (c.state === 'revealed' ? i : -1))
          .filter((i) => i >= 0)
        if (nowRevealed.length === 2) {
          setMoves((m) => m + 1)
          const [a, b] = nowRevealed
          if (isMatch(next[a], next[b])) {
            return next.map((c, i) =>
              i === a || i === b ? { ...c, state: 'matched' as CardState } : c
            )
          }
          return next
        }
        return next
      })
    },
    [phase, cards, flippedIndices.length, isMatch]
  )

  const twoRevealedNoMatch =
    flippedIndices.length === 2 &&
    !isMatch(cards[flippedIndices[0]], cards[flippedIndices[1]])

  useEffect(() => {
    if (!twoRevealedNoMatch) return
    const t = setTimeout(() => {
      setCards((prev) =>
        prev.map((c) => (c.state === 'revealed' ? { ...c, state: 'hidden' as CardState } : c))
      )
    }, 800)
    return () => clearTimeout(t)
  }, [twoRevealedNoMatch])

  const allMatched = cards.length > 0 && cards.every((c) => c.state === 'matched')
  const totalPairs = deck.length / 2

  useEffect(() => {
    if (phase !== 'playing' || !allMatched || completedRef.current) return
    completedRef.current = true
    setPhase('done')
    const score = Math.max(0, Math.min(1, 1 - (moves - totalPairs) * 0.05))
    onComplete?.({
      score,
      subscores: [
        { label: 'Moves', value: moves },
        { label: 'Pairs', value: totalPairs },
      ],
    })
  }, [phase, allMatched, moves, totalPairs, onComplete])

  const gridCols = (n: number) => (n <= 4 ? 2 : n <= 8 ? 4 : 4)

  if (phase === 'intro') {
    return (
      <div className="imagepair-intro">
        <p className="prompt">{exercise.prompt}</p>
        {showInstruction && (
          <p className="imagepair-instruction">
            Find pairs: same <strong>background</strong> and same <strong>image</strong>.
          </p>
        )}
        <button type="button" onClick={startGame} className="imagepair-start-btn" autoFocus>
          Start
        </button>
      </div>
    )
  }

  if (phase === 'done') {
    return (
      <div className="imagepair-done">
        <p className="imagepair-result">All pairs matched!</p>
        <p className="imagepair-stats">Total moves: {moves}</p>
      </div>
    )
  }

  return (
    <div className="imagepair-playing">
      <div
        className="imagepair-grid"
        style={{ gridTemplateColumns: `repeat(${gridCols(cards.length)}, 1fr)` }}
      >
        {cards.map((card, index) => (
          <button
            key={`${index}-${card.backgroundId}-${card.imageId}`}
            type="button"
            className={`imagepair-card ${card.state}`}
            style={{
              backgroundColor: card.state !== 'hidden' && card.backgroundColorHex ? card.backgroundColorHex : undefined,
            }}
            onClick={() => handleCardClick(index)}
            disabled={
              card.state === 'matched' ||
              (flippedIndices.length >= 2 && card.state === 'hidden')
            }
          >
            {card.state === 'hidden' ? '?' : card.imageId}
          </button>
        ))}
      </div>
      <p className="imagepair-moves">Moves: {moves}</p>
    </div>
  )
}
